#This Travis config template file was taken from https://github.com/FriendsOfCake/travis
language: php

php:
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

after_script:
  - sh -c "cat build/logs/clover.xml"

notifications:
email: true
